export const LOGIN = "Login";
export const REGISTER = "Register";
export const LOGIN_BUTTON = "login";
export const REGISTER_BUTTON = "register";
export const LOGIN_EMAIL_PLACEHOLDER = "please enter your email";
export const LOGIN_NAME_PLACEHOLDER = "please enter your full Name";
export const LOGIN_PASSWORD_PLACEHOLDER ="please enter your password"
export const LOGIN_QUESTION = "Didn't have an account?";
export const LOGIN_REGISTER ='Register here';
export const REGISTER_QUESTION = "Already have an account?";
export const REGISTER_LOGIN = 'Login Here';
